[tool.poetry]
name = "kalokohan"
version = "0.1.0"
description = ""
authors = ["boggs <hello@boggs.xyz>"]
readme = "README.md"
packages = [{include = "kalokohan"}]

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.7"
django-extensions = "^3.2.3"
gunicorn = "^21.2.0"
dj-database-url = "^2.1.0"
whitenoise = "^6.6.0"
psycopg = "^3.1.13"
sentry-sdk = "^1.38.0"
factory-boy = "^3.3.0"
django-ninja = "^1.0.1"
django-solo = "^2.1.0"
requests = "^2.31.0"
responses = "~0.24.1"
prometheus-client = "~0.19.0"
facebook-scraper = "^0.2.59"

[tool.poetry.group.dev.dependencies]
black = "^23.11.0"
ruff = "^0.1.1"
pre-commit = "^3.5.0"
bandit = "^1.7.5"
detect-secrets = "^1.4.0"
djhtml = "^3.0.6"
dslr = {version="~0.4.0", extras=["psycopg2-binary"]}
django-types = "~0.19.1"
pyright = "^1.1.337"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
select = ["E", "F", "W", "C90", "I"]

[tool.ruff.per-file-ignores]
"kalokohan/*/migrations/*.py" = ["E501"]

[tool.bandit]
exclude_dirs = ["tests"]
