[tool.poetry]
name = "kalokohan"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "kalokohan"}]

[tool.poetry.dependencies]
python = "^3.11"
django = {git = "https://github.com/django/django.git"}
django-extensions = "^3.2.1"
gunicorn = "^20.1.0"
dj-database-url = "^1.0.0"
whitenoise = "^6.2.0"
psycopg2 = "^2.9.5"
sentry-sdk = "^1.11.1"
factory-boy = "^3.2.1"
django-ninja = "^0.19.1"
django-solo = "^2.0.0"
requests = "^2.28.1"
responses = "^0.22.0"
prometheus-client = "^0.15.0"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
isort = "^5.10.1"
flake8 = "^5.0.4"
pre-commit = "^2.20.0"
bandit = "^1.7.4"
detect-secrets = "^1.4.0"
django-types = "^0.16.0"
poetryup = "^0.12.5"
dslr = "^0.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
