[tool.poetry]
name = "kalokohan"
version = "0.1.0"
description = ""
authors = ["boggs <hello@boggs.xyz>"]
readme = "README.md"
packages = [{include = "kalokohan"}]

[tool.poetry.dependencies]
python = "^3.11"
django = {version = "^5.0a1", allow-prereleases = true}
django-extensions = "^3.2.3"
gunicorn = "^21.2.0"
dj-database-url = "^2.1.0"
whitenoise = "^6.5.0"
psycopg = "^3.1.10"
sentry-sdk = "^1.31.0"
factory-boy = "^3.3.0"
django-ninja = "^0.22.2"
django-solo = "^2.1.0"
requests = "^2.31.0"
responses = "^0.23.3"
prometheus-client = "^0.17.1"
facebook-scraper = "^0.2.59"

[tool.poetry.group.dev.dependencies]
black = "^23.9.1"
ruff = "^0.0.290"
pre-commit = "^3.4.0"
bandit = "^1.7.5"
detect-secrets = "^1.4.0"
djhtml = "^3.0.6"
dslr = {version="^0.4.0", extras=["psycopg2-binary"]}
django-types = "^0.17.0"
pyright = "^1.1.327"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
select = ["E", "F", "W", "C90", "I"]

[tool.ruff.per-file-ignores]
"kalokohan/*/migrations/*.py" = ["E501"]

[tool.bandit]
exclude_dirs = ["tests"]
