[tool.poetry]
name = "kalokohan"
version = "0.1.0"
description = ""
authors = ["boggs <hello@boggs.xyz>"]
readme = "README.md"
packages = [{include = "kalokohan"}]

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.11"
django-extensions = "^3.2.3"
gunicorn = "^21.2.0"
dj-database-url = "^2.1.0"
whitenoise = "^6.6.0"
psycopg = "^3.1.18"
sentry-sdk = "^1.43.0"
factory-boy = "^3.3.0"
django-ninja = "^1.1.0"
django-solo = "^2.2.0"
requests = "^2.31.0"
responses = "^0.25.0"
prometheus-client = "^0.20.0"
facebook-scraper = "^0.2.59"

[tool.poetry.group.dev.dependencies]
ruff = "*"
pre-commit = "^3.6.2"
bandit = "^1.7.8"
detect-secrets = "^1.4.0"
djhtml = "^3.0.6"
dslr = {version="*", extras=["psycopg2-binary"]}
django-types = "*"
pyright = "^1.1.353"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.lint]
select = ["E", "F", "W", "C90", "I"]

[tool.ruff.lint.per-file-ignores]
"kalokohan/*/migrations/*.py" = ["E501"]

[tool.bandit]
exclude_dirs = ["tests"]
