[tool.poetry]
name = "kalokohan"
version = "0.1.0"
description = ""
authors = ["boggs <hello@boggs.xyz>"]
readme = "README.md"
packages = [{include = "kalokohan"}]

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.16"
django-extensions = "^3.2.3"
gunicorn = "^22.0.0"
dj-database-url = "^2.2.0"
whitenoise = "^6.7.0"
psycopg = "^3.2.1"
sentry-sdk = "^2.13.0"
factory-boy = "^3.3.1"
django-ninja = "^1.3.0"
django-solo = "^2.3.0"
requests = "^2.32.3"
responses = "*"
prometheus-client = "^0.20.0"

[tool.poetry.group.dev.dependencies]
ruff = "*"
pre-commit = "^3.8.0"
bandit = "^1.7.9"
detect-secrets = "^1.5.0"
djhtml = "^3.0.6"
dslr = {version="*", extras=["psycopg2-binary"]}
django-types = "*"
pyright = "^1.1.377"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.lint]
select = ["E", "F", "W", "C90", "I"]

[tool.ruff.lint.per-file-ignores]
"kalokohan/*/migrations/*.py" = ["E501"]

[tool.bandit]
exclude_dirs = ["tests"]
