[tool.poetry]
name = "kalokohan"
version = "0.1.0"
description = ""
authors = ["boggs <hello@boggs.xyz>"]
readme = "README.md"
packages = [{include = "kalokohan"}]

[tool.poetry.dependencies]
python = "^3.12"
django = {version = "^4.2b1", allow-prereleases = true}
django-extensions = "^3.2.1"
gunicorn = "^20.1.0"
dj-database-url = "^1.2.0"
whitenoise = "^6.4.0"
psycopg = "^3.1.8"
sentry-sdk = "^1.16.0"
factory-boy = "^3.2.1"
django-ninja = "^0.21.0"
django-solo = "^2.0.0"
requests = "^2.28.2"
responses = "^0.23.1"
prometheus-client = "^0.16.0"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
ruff = "^0.0.254"
pre-commit = "^3.1.1"
bandit = "^1.7.5"
detect-secrets = "^1.4.0"
djhtml = "^3.0.5"
dslr = "^0.4.0"
django-types = "^0.17.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
select = ["E", "F", "W", "C90", "I"]

[tool.ruff.per-file-ignores]
"kalokohan/*/migrations/*.py" = ["E501"]
