# Generated by Django 4.2.5 on 2023-09-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "API configuration",
            },
        ),
        migrations.CreateModel(
            name="WeightItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight_lbs", models.DecimalField(decimal_places=2, max_digits=5)),
                ("weighed_at", models.DateField()),
            ],
            options={
                "ordering": ["-weighed_at"],
            },
        ),
    ]
