# Generated by Django 3.2.16 on 2022-10-28 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="logitem",
            old_name="source",
            new_name="log_source",
        ),
        migrations.RenameField(
            model_name="logitem",
            old_name="type",
            new_name="log_type",
        ),
    ]
