# Generated by Django 4.1.2 on 2022-11-02 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallpapers", "0002_pastrandomphoto"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Config",
        ),
    ]
